services:
  backend:
    build: ./backend 
    image: backend-image
    expose:
      - "8000"

  gateway:
    build: 
      context: .
      dockerfile: gateway/Dockerfile
    image: gateway-image
    ports:
      - "80:80"
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus:v2.53.1
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./observability/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - "3000:3000"
    volumes:
      - ./observability/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./observability/grafana/data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus