services:
  backend:
    build: ./backend 
    image: backend-image
    expose:
      - "8000"

  gateway:
    build: 
      context: .
      dockerfile: gateway/Dockerfile
    image: gateway-image
    ports:
      - "80:80"
    depends_on:
      - backend