{
 "title": "SUT API Server Health",
 "description": "Latency, Error, Saturation, Traffic (Golden Signals) for the SUT API server.",
 "tags": [
  "sut",
  "api-server",
  "latency",
  "errors",
  "traffic",
  "saturation"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Errors\n" } },
  {
   "title": "Availability (%)",
   "type": "timeseries",
   "description": "Percentage of non server errors (5XX) over the time interval.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "(sum(rate(http_request_duration_ms_count{status_code!~\"5..\"}[1m])) * 100) / sum(rate(http_request_duration_ms_count[1m]))",
     "legendFormat": "Availability"
    }
   ]
  },
  {
   "title": "Errors by Endpoint",
   "type": "timeseries",
   "description": "HTTP 5XX error rate by endpoint.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(http_request_duration_ms_count{status_code=~\"5..\"}[1m])",
     "legendFormat": "Errors"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 }, "options": { "content": "# Traffic\n" } },
  {
   "title": "HTTP Responses by Status",
   "type": "timeseries",
   "description": "Rate of HTTP Responses by returned status code.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "clamp_min(sum by(status_code) (rate(http_request_duration_ms_count[1m])), 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Responses by Endpoint",
   "type": "timeseries",
   "description": "Rate of HTTP Responses by endpoint.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "clamp_min(sum by(endpoint) (rate(http_request_duration_ms_count[1m])), 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 34 }, "options": { "content": "# Saturation\n" } },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 36 }, "options": { "content": "# Latency\n" } },
  {
   "title": "Latency Percentiles by Endpoint",
   "type": "gauge",
   "description": "P99, P90, P50 for the latency of requests by endpoint \nover the time interval.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, endpoint) (rate(http_request_duration_ms_bucket[1m])))",
     "legendFormat": "P99 {{endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, endpoint) (rate(http_request_duration_ms_bucket[1m])))",
     "legendFormat": "P90 {{endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, endpoint) (rate(http_request_duration_ms_bucket[1m])))",
     "legendFormat": "P50 {{endpoint}}"
    }
   ]
  },
  {
   "title": "Latency Percentiles (Gauge)",
   "type": "bargauge",
   "description": "P99, P90, P50 for the latency of requests over the time interval.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_request_duration_ms_bucket[1m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(http_request_duration_ms_bucket[1m])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_request_duration_ms_bucket[1m])))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Latency Percentiles",
   "type": "timeseries",
   "description": "P99, P90, P50 for the latency of requests over the time interval.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_request_duration_ms_bucket[1m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(http_request_duration_ms_bucket[1m])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_request_duration_ms_bucket[1m])))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Latency Percentiles by Endpoint",
   "type": "timeseries",
   "description": "P50, P90, P99 for the latency of requests by endpoint over the time interval.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, endpoint) (rate(http_request_duration_ms_bucket[1m])))",
     "legendFormat": "P99 {{endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, endpoint) (rate(http_request_duration_ms_bucket[1m])))",
     "legendFormat": "P90 {{endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, endpoint) (rate(http_request_duration_ms_bucket[1m])))",
     "legendFormat": "P50 {{endpoint}}"
    }
   ]
  }
 ]
}